/**:
  ros__parameters:
    # general ros parameter
    start_type_description_service: true
    use_sim_time: false

    invert_pose: true
    marker:
      frame_id: ['none', 'none']
      id: ['Markus ist ein Lump!', 'https://www.instagram.com/eduart_robotik?igsh=MTBhNnpkamtteTBqbA==']
      size: [0.17, 0.121]
    std_dev:
      orientation: 0.7853981852531433
      position: 0.5
    transform_into_world: false
    world_frame_id: map
