/**:
  ros__parameters:
    # general ros parameter
    use_sim_time: false
    start_type_description_service: true

    # input filter settings (pose feedback)
    input:
      filter:
        enable: true
        weight: 0.5
      timeout:
        enable: true
        value: 300

    # pid controller for pose controlling
    pid:
      angular:
        kd: 0.0
        ki: 0.0
        kp: 0.75
        limit: 0.2
        input_filter_weight: 1.0
        use_anti_windup: true

      linear:
        kd: 0.0
        ki: 0.0
        kp: 0.75
        limit: 0.2
        input_filter_weight: 0.3
        use_anti_windup: true
