version: "3.0"

services:
  eduart-swarm-slave:
    image: eduartrobotik/eduart-swarm:0.2.0
    container_name: eduart-swarm-slave-0.2.0
    user: user
    restart: always
    privileged: true
    ipc: host
    pid: host
    mem_limit: 300mb
    environment:
        - EDU_ROBOT_NAMESPACE=${EDU_ROBOT_NAMESPACE}
    network_mode: "host"
    command: bash -c 'cd /home/user/ros/launch_content; ros2 launch eduard-fleet-drive-slave.launch.py'
    volumes:
        - './launch_content:/home/user/ros/launch_content:r'
