/**:
  ros__parameters:
    use_sim_time: false

    number_of_robots: 3

    robot_0:
      name: 'eduard/blue'
      x: 0.4
      y: 0.0
      yaw: 0.0

    robot_1:
      name: 'eduard/green'
      x: -0.30
      y:  0.34
      yaw: -0.671951762 #

    robot_2:
      name: 'eduard/red'
      x: -0.30
      y:  -0.34
      yaw: 0.671951762 # 30°
