/**:
  ros__parameters:
    use_sim_time: false
    frame_robot: 'eduard/green/base_link'

    pid:
      angular:
        kd: 0.0
        ki: 0.0
        kp: -1.0
        limit: 0.2
        use_anti_windup: true
      linear:
        kd: 0.0
        ki: 0.0
        kp: -1.0
        limit: 0.2
        use_anti_windup: true

    set_point:
      x: 0.7
      y: 0.0
      yaw: 0.0
