version: "2.4"

services:
  eduart-swarm-master:
    image: eduartrobotik/eduart-swarm:0.2.0
    container_name: eduart-swarm-slave-0.2.0
    user: user
    restart: always
    privileged: true
    ipc: host
    pid: host
    mem_limit: 300mb
    command: bash -c 'ros2 launch edu_swarm eduard-green-fleet-drive-slave.launch.py'
    environment:
        - EDU_ROBOT_NAMESPACE=eduard/green    
    networks:
        - proxy-redirect
        - zzz_layer2_net1

networks:
    proxy-redirect:
        external: true
    zzz_layer2_net1:
        name: zzz_layer2_net1
        external: true
