version: "2.4"

services:
  eduart-swarm-master:
    image: eduartrobotik/eduart-swarm:0.2.1
    container_name: eduart-swarm-master-0.2.1
    user: user
    restart: always
    privileged: true
    ipc: host
    pid: host
    mem_limit: 300mb
    command: bash -c 'ros2 launch edu_swarm eduard-fleet-drive-master.launch.py'
    networks:
        - proxy-redirect
        - zzz_layer2_net1
        # - zzz_layer2_net2

networks:
    proxy-redirect:
        external: true
    zzz_layer2_net1:
        name: zzz_layer2_net1
        external: true
