version: "3.0"

services:
    leuze-safety:
        image: eduartrobotik/eduart-fleet:0.3.0
        container_name: leuze-safety-3.0.0
        user: root
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=${EDU_ROBOT_NAMESPACE}
            - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}
            - CYCLONEDDS_URI=/home/user/ros/launch_content/cyclone_profile.xml         
        network_mode: "host"
        command: bash -c 'cd /home/user/ros/launch_content; ros2 launch collision_avoidance.launch.py'
        volumes:
            - './launch_content:/home/user/ros/launch_content:r'
